name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

permissions:
  contents: read

concurrency:
  group: ci-${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  unit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync

      - name: Run unit tests
        run: uv run pytest -q -m "not integration"

  integration:
    runs-on: ubuntu-latest
    needs: unit
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Sync dependencies
        run: uv sync

      - name: Run integration tests
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          OPENAI_BASE_URL: ${{ secrets.OPENAI_BASE_URL }}
          MODEL_ID: ${{ secrets.MODEL_ID }}
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          if [ -z "${{ secrets.OPENAI_BASE_URL }}" ]; then
            echo "OPENAI_BASE_URL not set; skipping integration tests";
            exit 0;
          fi
          uv run pytest -q -m integration

